// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoEXd3KrL2ZVCKG7mmeCVAOS2PvCXSFF8',
    appId: '1:409995153841:web:75fa2bb7713f7b8b682d90',
    messagingSenderId: '409995153841',
    projectId: 'lift-sync-ca841',
    authDomain: 'lift-sync-ca841.firebaseapp.com',
    storageBucket: 'lift-sync-ca841.appspot.com',
    measurementId: 'G-8Y43151W6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJQOiYI4kzo-HnYnXWmJIv1qu3ZFu2Vk',
    appId: '1:409995153841:android:267badba4ac81c26682d90',
    messagingSenderId: '409995153841',
    projectId: 'lift-sync-ca841',
    storageBucket: 'lift-sync-ca841.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJO9JVvU_ACZG3ZIflBkDw18M0DB8Z8Js',
    appId: '1:409995153841:ios:9347d2d7be773882682d90',
    messagingSenderId: '409995153841',
    projectId: 'lift-sync-ca841',
    storageBucket: 'lift-sync-ca841.appspot.com',
    iosBundleId: 'com.example.liftSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJO9JVvU_ACZG3ZIflBkDw18M0DB8Z8Js',
    appId: '1:409995153841:ios:17b5e4bb5fa9872e682d90',
    messagingSenderId: '409995153841',
    projectId: 'lift-sync-ca841',
    storageBucket: 'lift-sync-ca841.appspot.com',
    iosBundleId: 'com.example.liftSync.RunnerTests',
  );
}
